import { imageViewerMeta } from "./resources/image-viewer.js";

const RO = { readOnlyHint: true, destructiveHint: false, openWorldHint: false };
const WA = { readOnlyHint: false, destructiveHint: false, openWorldHint: false };
const imageMeta = imageViewerMeta();

export function buildBrowserToolDefinitions() {
  return [
    { name: "browser.status", description: "Return browser CDP backend availability, port range, and known sessions.", inputSchema: { type: "object", properties: {} }, annotations: RO },
    { name: "browser.start", description: "Start an isolated Chrome DevTools Protocol browser session using local-dev-mcp profile and port range.", inputSchema: { type: "object", properties: { url: { type: "string" }, session_id: { type: "string" } } }, annotations: WA },
    { name: "browser.sessions", description: "List known browser CDP sessions for the selected project.", inputSchema: { type: "object", properties: {} }, annotations: RO },
    { name: "browser.stop", description: "Stop a browser CDP session and remove it from local-dev-mcp session state.", inputSchema: { type: "object", properties: { session_id: { type: "string" } } }, annotations: WA },
    { name: "browser.tabs", description: "List page targets/tabs for a browser CDP session.", inputSchema: { type: "object", properties: { session_id: { type: "string" } } }, annotations: RO },
    { name: "browser.dom", description: "Return DOM text and HTML for a selector in a browser CDP session.", inputSchema: { type: "object", properties: { session_id: { type: "string" }, selector: { type: "string" } } }, annotations: RO },
    { name: "browser.selectors", description: "Return interactive selector candidates from a browser CDP session.", inputSchema: { type: "object", properties: { session_id: { type: "string" }, limit: { type: "integer", minimum: 1, maximum: 500 }, query: { type: "string" } } }, annotations: RO },
    { name: "browser.click", description: "Click an element by CSS selector in a browser CDP session and return an after-action screenshot by default.", _meta: imageMeta, inputSchema: { type: "object", properties: { session_id: { type: "string" }, selector: { type: "string" }, observe: { type: "string", enum: ["none", "after"] }, wait_ms: { type: "integer", minimum: 0, maximum: 10000 } }, required: ["selector"] }, annotations: WA },
    { name: "browser.type", description: "Set text on an input-like element by CSS selector in a browser CDP session and return an after-action screenshot by default.", _meta: imageMeta, inputSchema: { type: "object", properties: { session_id: { type: "string" }, selector: { type: "string" }, text: { type: "string" }, submit: { type: "boolean" }, observe: { type: "string", enum: ["none", "after"] }, wait_ms: { type: "integer", minimum: 0, maximum: 10000 } }, required: ["selector", "text"] }, annotations: WA },
    { name: "browser.wait", description: "Wait for a selector and/or text to appear in a browser CDP session.", inputSchema: { type: "object", properties: { session_id: { type: "string" }, selector: { type: "string" }, text: { type: "string" }, url_contains: { type: "string" }, title_contains: { type: "string" }, timeout_ms: { type: "integer", minimum: 1, maximum: 60000 } } }, annotations: RO },
    { name: "browser.eval", description: "Evaluate JavaScript in a browser CDP session and return the JSON-serializable result.", inputSchema: { type: "object", properties: { session_id: { type: "string" }, expression: { type: "string" } }, required: ["expression"] }, annotations: WA },
    { name: "browser.press", description: "Dispatch a key press in a browser CDP session, optionally focusing a selector first, and return an after-action screenshot by default.", _meta: imageMeta, inputSchema: { type: "object", properties: { session_id: { type: "string" }, key: { type: "string" }, selector: { type: "string" }, observe: { type: "string", enum: ["none", "after"] }, wait_ms: { type: "integer", minimum: 0, maximum: 10000 } }, required: ["key"] }, annotations: WA },
    { name: "browser.reload", description: "Reload the active page in a browser CDP session and return an after-action screenshot by default.", _meta: imageMeta, inputSchema: { type: "object", properties: { session_id: { type: "string" }, observe: { type: "string", enum: ["none", "after"] }, wait_ms: { type: "integer", minimum: 0, maximum: 10000 } } }, annotations: WA },
    { name: "browser.back", description: "Navigate back in the active browser CDP session history and return an after-action screenshot by default.", _meta: imageMeta, inputSchema: { type: "object", properties: { session_id: { type: "string" }, observe: { type: "string", enum: ["none", "after"] }, wait_ms: { type: "integer", minimum: 0, maximum: 10000 } } }, annotations: WA },
    { name: "browser.forward", description: "Navigate forward in the active browser CDP session history and return an after-action screenshot by default.", _meta: imageMeta, inputSchema: { type: "object", properties: { session_id: { type: "string" }, observe: { type: "string", enum: ["none", "after"] }, wait_ms: { type: "integer", minimum: 0, maximum: 10000 } } }, annotations: WA },
    { name: "browser.screenshot", description: "Capture a screenshot from the active Chrome DevTools Protocol page session.", inputSchema: { type: "object", properties: { session_id: { type: "string" } } }, annotations: RO },
    { name: "browser.open", description: "Navigate a Chrome DevTools Protocol browser session to an http/https URL and return an after-action screenshot by default.", _meta: imageMeta, inputSchema: { type: "object", properties: { url: { type: "string" }, session_id: { type: "string" }, observe: { type: "string", enum: ["none", "after"] }, wait_ms: { type: "integer", minimum: 0, maximum: 10000 } }, required: ["url"] }, annotations: WA },
  ];
}
