const RO = { readOnlyHint: true, destructiveHint: false, openWorldHint: false };
const MUT = { readOnlyHint: false, destructiveHint: false, openWorldHint: false };

export function buildMobileToolDefinitions() {
  return [
    { name: "mobile.status", description: "Return mobile backend availability and discovered simulators, emulators, and physical devices.", inputSchema: { type: "object", properties: {} }, annotations: RO },
    { name: "mobile.list_devices", description: "List iOS Simulator, physical iOS, and Android devices visible to local-dev-mcp.", inputSchema: { type: "object", properties: {} }, annotations: RO },
    { name: "mobile.screenshot", description: "Capture a screenshot from an iOS Simulator, physical iOS device, or Android device and return image metadata/path.", inputSchema: { type: "object", properties: { device: { type: "string" } } }, annotations: RO },
    { name: "mobile.snapshot", description: "Capture the iOS or Android accessibility tree through agent-device. Optionally filter by text, identifier, type, or ref.", inputSchema: { type: "object", properties: { device: { type: "string" }, query: { type: "string" }, limit: { type: "integer", minimum: 1, maximum: 1000 } } }, annotations: RO },
    { name: "mobile.boot", description: "Boot an iOS Simulator and open the Simulator app. Physical iOS devices do not need booting.", inputSchema: { type: "object", properties: { device: { type: "string" } } }, annotations: MUT },
    { name: "mobile.launch_app", description: "Launch an app by name or bundle ID on iOS, or package name on Android, and return an after-action screenshot by default.", inputSchema: { type: "object", properties: { device: { type: "string" }, app: { type: "string" }, observe: { type: "string", enum: ["none", "after"] } }, required: ["app"] }, annotations: MUT },
    { name: "mobile.open_url", description: "Open a URL on an iOS Simulator, physical iOS device, or Android device and return an after-action screenshot by default.", inputSchema: { type: "object", properties: { device: { type: "string" }, url: { type: "string" }, observe: { type: "string", enum: ["none", "after"] } }, required: ["url"] }, annotations: MUT },
    { name: "mobile.tap", description: "Tap coordinates on an iOS Simulator, physical iOS device, or Android device and return an after-action screenshot by default.", inputSchema: { type: "object", properties: { device: { type: "string" }, x: { type: "number" }, y: { type: "number" }, observe: { type: "string", enum: ["none", "after"] } }, required: ["x", "y"] }, annotations: MUT },
    { name: "mobile.tap_element", description: "Tap an iOS or Android accessibility element using a snapshot ref, visible text, or agent-device selector.", inputSchema: { type: "object", properties: { device: { type: "string" }, target: { type: "string" }, observe: { type: "string", enum: ["none", "after"] } }, required: ["target"] }, annotations: MUT },
    { name: "mobile.type", description: "Type text on an iOS Simulator, physical iOS device, or Android device and return an after-action screenshot by default.", inputSchema: { type: "object", properties: { device: { type: "string" }, text: { type: "string" }, observe: { type: "string", enum: ["none", "after"] } }, required: ["text"] }, annotations: MUT },
    { name: "mobile.swipe", description: "Swipe between two coordinates on iOS or Android and return an after-action screenshot by default.", inputSchema: { type: "object", properties: { device: { type: "string" }, x1: { type: "number" }, y1: { type: "number" }, x2: { type: "number" }, y2: { type: "number" }, duration_ms: { type: "integer", minimum: 0, maximum: 60000 }, observe: { type: "string", enum: ["none", "after"] } }, required: ["x1", "y1", "x2", "y2"] }, annotations: MUT },
    { name: "mobile.press", description: "Press the Home or Back navigation action on iOS or Android.", inputSchema: { type: "object", properties: { device: { type: "string" }, key: { type: "string", enum: ["home", "back"] }, observe: { type: "string", enum: ["none", "after"] } }, required: ["key"] }, annotations: MUT },
    { name: "mobile.wait", description: "Wait on iOS or Android until text, a snapshot ref, or an agent-device selector appears.", inputSchema: { type: "object", properties: { device: { type: "string" }, target: { type: "string" }, timeout_ms: { type: "integer", minimum: 1, maximum: 60000 } }, required: ["target"] }, annotations: RO },
  ];
}
